version: '3.8'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ponder:
    build: .
    env_file:
      - .env
    ports:
      - "42071:42069"
    depends_on:
      - postgres
    restart: always

  shred-bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file:
      - .env
    depends_on:
      - postgres
      - ponder
    restart: always

volumes:
  pgdata: