export const MarketMakerABI: any[] = [
	{
		type: "constructor",
		inputs: [
			{ name: "name", type: "string", internalType: "string" },
			{ name: "symbol", type: "string", internalType: "string" },
			{ name: "_veToken", type: "address", internalType: "address" },
			{
				name: "_gaugeController",
				type: "address",
				internalType: "address",
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "activeBalance",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "allowance",
		inputs: [
			{ name: "owner", type: "address", internalType: "address" },
			{ name: "spender", type: "address", internalType: "address" },
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "approve",
		inputs: [
			{ name: "spender", type: "address", internalType: "address" },
			{ name: "value", type: "uint256", internalType: "uint256" },
		],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "balanceOf",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "decimals",
		inputs: [],
		outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "deposit",
		inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "getRewardTokens",
		inputs: [],
		outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "lastRewardBlock",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "name",
		inputs: [],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "redeemRewards",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "rewardState",
		inputs: [{ name: "", type: "address", internalType: "address" }],
		outputs: [
			{ name: "index", type: "uint128", internalType: "uint128" },
			{ name: "lastBalance", type: "uint128", internalType: "uint128" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "symbol",
		inputs: [],
		outputs: [{ name: "", type: "string", internalType: "string" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalActiveSupply",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "totalSupply",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "transfer",
		inputs: [
			{ name: "to", type: "address", internalType: "address" },
			{ name: "value", type: "uint256", internalType: "uint256" },
		],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "transferFrom",
		inputs: [
			{ name: "from", type: "address", internalType: "address" },
			{ name: "to", type: "address", internalType: "address" },
			{ name: "value", type: "uint256", internalType: "uint256" },
		],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "userReward",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
		],
		outputs: [
			{ name: "index", type: "uint128", internalType: "uint128" },
			{ name: "accrued", type: "uint128", internalType: "uint128" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "withdraw",
		inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "Approval",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "spender",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RedeemRewards",
		inputs: [
			{
				name: "user",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "rewardsOut",
				type: "uint256[]",
				indexed: false,
				internalType: "uint256[]",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Transfer",
		inputs: [
			{
				name: "from",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "to",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "value",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "error",
		name: "ERC20InsufficientAllowance",
		inputs: [
			{ name: "spender", type: "address", internalType: "address" },
			{ name: "allowance", type: "uint256", internalType: "uint256" },
			{ name: "needed", type: "uint256", internalType: "uint256" },
		],
	},
	{
		type: "error",
		name: "ERC20InsufficientBalance",
		inputs: [
			{ name: "sender", type: "address", internalType: "address" },
			{ name: "balance", type: "uint256", internalType: "uint256" },
			{ name: "needed", type: "uint256", internalType: "uint256" },
		],
	},
	{
		type: "error",
		name: "ERC20InvalidApprover",
		inputs: [{ name: "approver", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "ERC20InvalidReceiver",
		inputs: [{ name: "receiver", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "ERC20InvalidSender",
		inputs: [{ name: "sender", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "ERC20InvalidSpender",
		inputs: [{ name: "spender", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "SafeERC20FailedOperation",
		inputs: [{ name: "token", type: "address", internalType: "address" }],
	},
];
