/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */

interface ContractDetails {
	address: string;
	abi: any[];
	inheritedFunctions?: any;
}

interface DeployedContracts {
	[chainId: string]: {
		[contractName: string]: ContractDetails;
	};
}

export const deployedContracts: DeployedContracts = {
	31337: {
		BalanceManager: {
			address: "0x9a676e781a523b5d0c0e43731313a708cb607508",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "_feeReceiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "_feeMaker",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_feeTaker",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "balanceOf",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "balance",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "deposit",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "deposit",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "feeMaker",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "feeTaker",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
					],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getLockedBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
					],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "lock",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "lockedBalanceOf",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "owner",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "renounceOwnership",
					inputs: [],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setAuthorizedOperator",
					inputs: [
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "approved",
							type: "bool",
							internalType: "bool",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setFees",
					inputs: [
						{
							name: "_feeMaker",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_feeTaker",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferFrom",
					inputs: [
						{
							name: "sender",
							type: "address",
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferLockedFrom",
					inputs: [
						{
							name: "sender",
							type: "address",
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferOwnership",
					inputs: [
						{
							name: "newOwner",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "unlock",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "withdraw",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "withdraw",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "event",
					name: "Deposit",
					inputs: [
						{
							name: "user",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: true,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "OperatorSet",
					inputs: [
						{
							name: "operator",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "approved",
							type: "bool",
							indexed: false,
							internalType: "bool",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "OwnershipTransferred",
					inputs: [
						{
							name: "previousOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "newOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "TransferFrom",
					inputs: [
						{
							name: "operator",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "sender",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "Withdrawal",
					inputs: [
						{
							name: "user",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: true,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "error",
					name: "ERC20TransferFailed",
					inputs: [],
				},
				{
					type: "error",
					name: "InsufficientBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "want",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "have",
							type: "uint256",
							internalType: "uint256",
						},
					],
				},
				{
					type: "error",
					name: "NativeTransferFailed",
					inputs: [],
				},
				{
					type: "error",
					name: "OwnableInvalidOwner",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "OwnableUnauthorizedAccount",
					inputs: [
						{
							name: "account",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "ReentrancyGuardReentrantCall",
					inputs: [],
				},
				{
					type: "error",
					name: "TransferError",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
				},
				{
					type: "error",
					name: "UnauthorizedOperator",
					inputs: [
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "ZeroAmount",
					inputs: [],
				},
			],
			inheritedFunctions: {
				owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				renounceOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				transferOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
			},
		},
		PoolManager: {
			address: "0x0b306bf915c4d645ff596e518faf3f9669b97016",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "_balanceManager",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "createPool",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "_lotSize",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_maxOrderAmount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "getPool",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple",
							internalType: "struct IPoolManager.Pool",
							components: [
								{
									name: "maxOrderAmount",
									type: "uint256",
									internalType: "uint256",
								},
								{
									name: "lotSize",
									type: "uint256",
									internalType: "uint256",
								},
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "orderBook",
									type: "address",
									internalType: "contract IOrderBook",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getPoolId",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
					],
					outputs: [
						{
							name: "",
							type: "bytes32",
							internalType: "PoolId",
						},
					],
					stateMutability: "pure",
				},
				{
					type: "function",
					name: "owner",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "pools",
					inputs: [
						{
							name: "",
							type: "bytes32",
							internalType: "PoolId",
						},
					],
					outputs: [
						{
							name: "maxOrderAmount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "lotSize",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "baseCurrency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "quoteCurrency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "orderBook",
							type: "address",
							internalType: "contract IOrderBook",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "renounceOwnership",
					inputs: [],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setRouter",
					inputs: [
						{
							name: "_router",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferOwnership",
					inputs: [
						{
							name: "newOwner",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "event",
					name: "OwnershipTransferred",
					inputs: [
						{
							name: "previousOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "newOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "PoolCreated",
					inputs: [
						{
							name: "id",
							type: "bytes32",
							indexed: true,
							internalType: "PoolId",
						},
						{
							name: "orderBook",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "baseCurrency",
							type: "address",
							indexed: false,
							internalType: "Currency",
						},
						{
							name: "quoteCurrency",
							type: "address",
							indexed: false,
							internalType: "Currency",
						},
						{
							name: "lotSize",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
						{
							name: "maxOrderAmount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "error",
					name: "InvalidRouter",
					inputs: [],
				},
				{
					type: "error",
					name: "OwnableInvalidOwner",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "OwnableUnauthorizedAccount",
					inputs: [
						{
							name: "account",
							type: "address",
							internalType: "address",
						},
					],
				},
			],
			inheritedFunctions: {
				owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				renounceOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				transferOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				createPool: "src/interfaces/IPoolManager.sol",
				getPool: "src/interfaces/IPoolManager.sol",
				getPoolId: "src/interfaces/IPoolManager.sol",
				setRouter: "src/interfaces/IPoolManager.sol",
			},
		},
		GTXRouter: {
			address: "0x959922be3caee4b8cd9a407cc3ac1c251c2007b1",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_poolManager",
							type: "address",
							internalType: "address",
						},
						{
							name: "_balanceManager",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "balanceManager",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "contract IBalanceManager",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "cancelOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "getBestPrice",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple",
							internalType: "struct IOrderBook.PriceVolume",
							components: [
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "volume",
									type: "uint256",
									internalType: "uint256",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getNextBestPrices",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "count",
							type: "uint8",
							internalType: "uint8",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple[]",
							internalType: "struct IOrderBook.PriceVolume[]",
							components: [
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "volume",
									type: "uint256",
									internalType: "uint256",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getOrderQueue",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
					],
					outputs: [
						{
							name: "orderCount",
							type: "uint48",
							internalType: "uint48",
						},
						{
							name: "totalVolume",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getUserActiveOrders",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple[]",
							internalType: "struct IOrderBook.Order[]",
							components: [
								{
									name: "id",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "user",
									type: "address",
									internalType: "address",
								},
								{
									name: "next",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "prev",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "timestamp",
									type: "uint48",
									internalType: "uint48",
								},
								{
									name: "expiry",
									type: "uint48",
									internalType: "uint48",
								},
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "status",
									type: "uint8",
									internalType: "enum Status",
								},
								{
									name: "quantity",
									type: "uint128",
									internalType: "Quantity",
								},
								{
									name: "filled",
									type: "uint128",
									internalType: "Quantity",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "placeMarketOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeMarketOrderWithDeposit",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeOrderWithDeposit",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "poolManager",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "contract IPoolManager",
						},
					],
					stateMutability: "view",
				},
			],
			inheritedFunctions: {},
		},
	},
	11155931: {
		BalanceManager: {
			address: "0x9b4fd469b6236c27190749bfe3227b85c25462d7",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "_feeReceiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "_feeMaker",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_feeTaker",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "balanceOf",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "balance",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "deposit",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "deposit",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "feeMaker",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "feeTaker",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
					],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getLockedBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
					],
					outputs: [
						{
							name: "",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "lock",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "lockedBalanceOf",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "owner",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "renounceOwnership",
					inputs: [],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setAuthorizedOperator",
					inputs: [
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
						{
							name: "approved",
							type: "bool",
							internalType: "bool",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setFees",
					inputs: [
						{
							name: "_feeMaker",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_feeTaker",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferFrom",
					inputs: [
						{
							name: "sender",
							type: "address",
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferLockedFrom",
					inputs: [
						{
							name: "sender",
							type: "address",
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferOwnership",
					inputs: [
						{
							name: "newOwner",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "unlock",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [
						{
							name: "",
							type: "bool",
							internalType: "bool",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "withdraw",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "withdraw",
					inputs: [
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "event",
					name: "Deposit",
					inputs: [
						{
							name: "user",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: true,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "OperatorSet",
					inputs: [
						{
							name: "operator",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "approved",
							type: "bool",
							indexed: false,
							internalType: "bool",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "OwnershipTransferred",
					inputs: [
						{
							name: "previousOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "newOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "TransferFrom",
					inputs: [
						{
							name: "operator",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "sender",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "receiver",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "Withdrawal",
					inputs: [
						{
							name: "user",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							indexed: true,
							internalType: "uint256",
						},
						{
							name: "amount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "error",
					name: "ERC20TransferFailed",
					inputs: [],
				},
				{
					type: "error",
					name: "InsufficientBalance",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "id",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "want",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "have",
							type: "uint256",
							internalType: "uint256",
						},
					],
				},
				{
					type: "error",
					name: "NativeTransferFailed",
					inputs: [],
				},
				{
					type: "error",
					name: "OwnableInvalidOwner",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "OwnableUnauthorizedAccount",
					inputs: [
						{
							name: "account",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "ReentrancyGuardReentrantCall",
					inputs: [],
				},
				{
					type: "error",
					name: "TransferError",
					inputs: [
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
						{
							name: "currency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "amount",
							type: "uint256",
							internalType: "uint256",
						},
					],
				},
				{
					type: "error",
					name: "UnauthorizedOperator",
					inputs: [
						{
							name: "operator",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "ZeroAmount",
					inputs: [],
				},
			],
			inheritedFunctions: {
				owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				renounceOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				transferOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
			},
		},
		PoolManager: {
			address: "0x35234957aC7ba5d61257d72443F8F5f0C431fD00",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_owner",
							type: "address",
							internalType: "address",
						},
						{
							name: "_balanceManager",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "createPool",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "_lotSize",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "_maxOrderAmount",
							type: "uint256",
							internalType: "uint256",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "getPool",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple",
							internalType: "struct IPoolManager.Pool",
							components: [
								{
									name: "maxOrderAmount",
									type: "uint256",
									internalType: "uint256",
								},
								{
									name: "lotSize",
									type: "uint256",
									internalType: "uint256",
								},
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "orderBook",
									type: "address",
									internalType: "contract IOrderBook",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getPoolId",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
					],
					outputs: [
						{
							name: "",
							type: "bytes32",
							internalType: "PoolId",
						},
					],
					stateMutability: "pure",
				},
				{
					type: "function",
					name: "owner",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "pools",
					inputs: [
						{
							name: "",
							type: "bytes32",
							internalType: "PoolId",
						},
					],
					outputs: [
						{
							name: "maxOrderAmount",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "lotSize",
							type: "uint256",
							internalType: "uint256",
						},
						{
							name: "baseCurrency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "quoteCurrency",
							type: "address",
							internalType: "Currency",
						},
						{
							name: "orderBook",
							type: "address",
							internalType: "contract IOrderBook",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "renounceOwnership",
					inputs: [],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "setRouter",
					inputs: [
						{
							name: "_router",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "transferOwnership",
					inputs: [
						{
							name: "newOwner",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "event",
					name: "OwnershipTransferred",
					inputs: [
						{
							name: "previousOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "newOwner",
							type: "address",
							indexed: true,
							internalType: "address",
						},
					],
					anonymous: false,
				},
				{
					type: "event",
					name: "PoolCreated",
					inputs: [
						{
							name: "id",
							type: "bytes32",
							indexed: true,
							internalType: "PoolId",
						},
						{
							name: "orderBook",
							type: "address",
							indexed: true,
							internalType: "address",
						},
						{
							name: "baseCurrency",
							type: "address",
							indexed: false,
							internalType: "Currency",
						},
						{
							name: "quoteCurrency",
							type: "address",
							indexed: false,
							internalType: "Currency",
						},
						{
							name: "lotSize",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
						{
							name: "maxOrderAmount",
							type: "uint256",
							indexed: false,
							internalType: "uint256",
						},
					],
					anonymous: false,
				},
				{
					type: "error",
					name: "InvalidRouter",
					inputs: [],
				},
				{
					type: "error",
					name: "OwnableInvalidOwner",
					inputs: [
						{
							name: "owner",
							type: "address",
							internalType: "address",
						},
					],
				},
				{
					type: "error",
					name: "OwnableUnauthorizedAccount",
					inputs: [
						{
							name: "account",
							type: "address",
							internalType: "address",
						},
					],
				},
			],
			inheritedFunctions: {
				owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				renounceOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				transferOwnership:
					"lib/openzeppelin-contracts/contracts/access/Ownable.sol",
				createPool: "src/interfaces/IPoolManager.sol",
				getPool: "src/interfaces/IPoolManager.sol",
				getPoolId: "src/interfaces/IPoolManager.sol",
				setRouter: "src/interfaces/IPoolManager.sol",
			},
		},
		GTXRouter: {
			address: "0xed2582315b355ad0ffdf4928ca353773c9a588e3",
			abi: [
				{
					type: "constructor",
					inputs: [
						{
							name: "_poolManager",
							type: "address",
							internalType: "address",
						},
						{
							name: "_balanceManager",
							type: "address",
							internalType: "address",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "balanceManager",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "contract IBalanceManager",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "cancelOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					outputs: [],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "getBestPrice",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple",
							internalType: "struct IOrderBook.PriceVolume",
							components: [
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "volume",
									type: "uint256",
									internalType: "uint256",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getNextBestPrices",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "count",
							type: "uint8",
							internalType: "uint8",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple[]",
							internalType: "struct IOrderBook.PriceVolume[]",
							components: [
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "volume",
									type: "uint256",
									internalType: "uint256",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getOrderQueue",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
					],
					outputs: [
						{
							name: "orderCount",
							type: "uint48",
							internalType: "uint48",
						},
						{
							name: "totalVolume",
							type: "uint256",
							internalType: "uint256",
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "getUserActiveOrders",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "user",
							type: "address",
							internalType: "address",
						},
					],
					outputs: [
						{
							name: "",
							type: "tuple[]",
							internalType: "struct IOrderBook.Order[]",
							components: [
								{
									name: "id",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "user",
									type: "address",
									internalType: "address",
								},
								{
									name: "next",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "prev",
									type: "uint48",
									internalType: "OrderId",
								},
								{
									name: "timestamp",
									type: "uint48",
									internalType: "uint48",
								},
								{
									name: "expiry",
									type: "uint48",
									internalType: "uint48",
								},
								{
									name: "price",
									type: "uint64",
									internalType: "Price",
								},
								{
									name: "status",
									type: "uint8",
									internalType: "enum Status",
								},
								{
									name: "quantity",
									type: "uint128",
									internalType: "Quantity",
								},
								{
									name: "filled",
									type: "uint128",
									internalType: "Quantity",
								},
							],
						},
					],
					stateMutability: "view",
				},
				{
					type: "function",
					name: "placeMarketOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeMarketOrderWithDeposit",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeOrder",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "placeOrderWithDeposit",
					inputs: [
						{
							name: "key",
							type: "tuple",
							internalType: "struct PoolKey",
							components: [
								{
									name: "baseCurrency",
									type: "address",
									internalType: "Currency",
								},
								{
									name: "quoteCurrency",
									type: "address",
									internalType: "Currency",
								},
							],
						},
						{
							name: "price",
							type: "uint64",
							internalType: "Price",
						},
						{
							name: "quantity",
							type: "uint128",
							internalType: "Quantity",
						},
						{
							name: "side",
							type: "uint8",
							internalType: "enum Side",
						},
					],
					outputs: [
						{
							name: "orderId",
							type: "uint48",
							internalType: "OrderId",
						},
					],
					stateMutability: "nonpayable",
				},
				{
					type: "function",
					name: "poolManager",
					inputs: [],
					outputs: [
						{
							name: "",
							type: "address",
							internalType: "contract IPoolManager",
						},
					],
					stateMutability: "view",
				},
			],
			inheritedFunctions: {},
		},
	},
} as const;
